#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend Innocent.Sax
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 442842-web-01 100.26.167.104
        server 442842-web-02 100.25.160.145
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
