#!/usr/bin/env bash
# This script generates an RSA key pair with a passphrase.

# Set the filename for the private key
private_key="school"

# Number of bits in the created key
key_bits=4096

# Passphrase to protect the created key
passphrase="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $key_bits -f "$private_key" -N "$passphrase"

echo "RSA key pair generated successfully."
